### ISSUE TITLE
Chek segv in son (operators)

### ISSUE THREAD

**Issue by Freccia** [segfault-team/42sh#112]

**Comment by Draeyo** [comment]
??

**Comment by Freccia** [comment]
message du signal recu si le fils segv, c'est kenny qui mas dit d'ajouter, mais je sais pas exactement ce que c'est

**Comment by dh4rm4** [comment]
./a.out (qui segfault) && ls

**Comment by Freccia** [comment]
ls &&  ../LEL  && ls
ls &&  ls &&  ../LEL  && ls
ls && ../LEL 2>&1 | cat -e  || ls
lol &&  ../LEL  && ls

**Comment by Freccia** [comment]
Ok depuis mon dernier push les valeurs de retour sont correctes (meme quand le fils segv).
Il reste ce cas:
ls && ./LEL || ls || pwd

ce qu'il se passe c'est que le premier ls est execute, puis LEL qui segv puis on saute le ls et on tombe sur le pwd avec des valeurs qui lui permettent de s'executer.
Avez vous une solution?

**Comment by Draeyo** [comment]
dans ton exemple `ls && ./LEL || ls || pwd` , il a le comportement qu'on lui demande, le probleme ici c'est qu'on gere pas du tout par rapport au PRECEDENT operateur, du coup au lieu de lire `ls && (./LEL || ls || pwd)` il lit `(ls && [./LEL) || {ls] || pwd}` (je sais pas si le dernier exemple est clair, faut suivre les `() [] {}`)
