### ISSUE TITLE
Inihibitors

### ISSUE THREAD

**Issue by dh4rm4** [segfault-team/42sh#18]

**Comment by Freccia** [comment]
les guimets sont en place.
struct_strsplit_quote -> struct_strsplit_wo_quote (wo = without)
ft_strsplit_quote && ft_strsplit_wo_quote OK

Manque le '\' (backslash)

**Comment by Freccia** [comment]
Done. 
Faut mieux tester si jamais il y a des segv ou des conneries, mais sinon c'est bon.
