### ISSUE TITLE
Auto_completion

### ISSUE THREAD

**Issue by dh4rm4** [segfault-team/42sh#25]

**Comment by dh4rm4** [comment]
STANDARD:
    - pas de proposition de completion
    - manage la reduction des possibilite
             |-> ls tcaps_ctr -> ls tcaps_ctrl_
    - pas d'insertion de tabulation
    - pas de gestion des wild cards

NEXT:
    - gerer la recherhce dans l'historique via autocompletion
    - proposition de compltion
    - gestion des wild cards

**Comment by Draeyo** [comment]
Voir si integrer ft_select a l'autocompletion est faisable facilement.

**Comment by Draeyo** [comment]
Ayoub s'occupe donc d'integrer une partie du ft_select ce week-end

**Comment by dh4rm4** [comment]
deadline: mercredi 15/03/17
