### ISSUE TITLE
Parsing

### ISSUE THREAD

**Issue by Geoffrey42** [segfault-team/42sh#28]

**Comment by Geoffrey42** [comment]
Gestion des priorités dans la commande (notamment lors de la création de fichiers). ---------- DONE------------------ !

Gestion des cas où les redirections sont "collées" à la commande (pas d'espace).

Voir globbing.

**Comment by dh4rm4** [comment]
Exemple de sortie:
e->line avant parsing: "ls|grep srcs"
e->line apres parsing: "ls | grep src"

e->line avant parsing: "ls|grep srcs|wc -l|grep 1>>test1>test2>test3;pwd;echo boid;env"
e->line apres parsing: "ls | grep srcs | wc -l | grep 1 >> test1 > test2 > test3 ; pwd ; echo boid ; env"

e->line avant parsing: "echo \"boid" -> gestion des caractères d'echappement

by mehdi:
En entree:
> ls -la |wc -l |grep
En sortie un Double tableau :
[0] --> ls
[1] --> -la
[2] ---> |
[3] ---> wc
[4] ---> -l
[5] ---> grep
[6] ---> NULL

**Comment by Draeyo** [comment]
Yop, pour l'ajout des quotes j'ai une idee pour integrer ca facilement.

**Comment by Freccia** [comment]
je pense que cette Issue fait partie de l'issue Inhibitors.
Le parsing maintenant est coherent. Faut mieux tester avec des cas exotiques, mais ca marche en general.

**Comment by Draeyo** [comment]
`watch -n 5 'netstat -an | grep ":80"'`

**Comment by Freccia** [comment]
?

**Comment by mehdiSuperDev** [comment]
???

Envoyé de mon iPhone

Le 11 mars 2017 à 10:45, gvzr <notifications@github.com<mailto:notifications@github.com>> a écrit :


?

**Comment by dh4rm4** [comment]
Gestion des ![NUMBER}
Ex : 
`echo "!1"`
`echo !1`
`echo '!1'`
`echo \'!1\'`
`echo \"!1\"`
`echo !!`
