### ISSUE TITLE
Better read input

### ISSUE THREAD

**Issue by ayoubleg** [segfault-team/42sh#30]
The terminal actually read 3char from the input FD, it should not !
Some key have more than 3char and other less ... If we manage read char by char the copy/paste from system (cmd+v) will work fine.

Example :
Up arrow -> Move back in history
ESC+ [ + A -> Should do the same !

**Comment by Draeyo** [comment]
we already manage the case where more bytes have to be read, your example doesn't seem to work here. For the more bytes example, look at tcaps_ctrl_arrow(.c).

**Comment by ayoubleg** [comment]
Nope ! i tried the master branch on a crap terminal and i can't use any of "special keys" (arrows etc), because my term is old school and send an ESC (27 ascii) EOF (0) then the rest of the key, they just output as regular text here.

Just try to input manually
'ESC' then '[' then 'A' in a POSIX shell and you'll get it :D

**Comment by Draeyo** [comment]
Ok so we have to detect the `esc` key by the code `127, 0, 0` and read 2 more keys to complete the sequence.
