### ISSUE TITLE
History consistent with ctrl-c

### ISSUE THREAD

**Issue by Freccia** [segfault-team/42sh#38]
When you are in the middle of the history tab and you press ctrl-c, then TCAPS.hist_move is not reset

**Comment by Draeyo** [comment]
quelle branch ?

**Comment by Freccia** [comment]
freccia, mais elle est up avec redir_clean. Donc j'imagine que le truc est aussi dans votre branche. J'ai deja regle ca toute facon.

Ps: je pense que l'historique est vraiment bien fait. Voila faut dire les choses positives aussi

**Comment by Draeyo** [comment]
on a fait beaucoup de modifs sur le comportement de ctrl+c dans la branch rainamaha, le probleme sera toujours la mais beaucoup plus facile a regler du coup (1 ligne a ajouter)

**Comment by Freccia** [comment]
je ne comprends pas.
Moi aussi j'avais gere le ctrl-c.. juste il imprimait le prompt une fois de trop. Je n'avais trouve moyen de le regler. Mais la ligne est efface et le reste esrt propre.
Pour ca je vous dis de voir ce que j'ai fait et de merger.................
