### ISSUE TITLE
Bug in Cmd-V

### ISSUE THREAD

**Issue by Freccia** [segfault-team/42sh#43]
$> echo ' " "" """ '\' "\''" " \ \ \ \ \ " '"

oublie de inserer les deux derniers chars... j'ai teste sur redirections_clean et il y a aussi ce bug

**Comment by Freccia** [comment]
$> echo   \'  \"   ""  \"""  '\\' "\\''"   "   \\  \ \ \ \ \" \'"

oublie de inserer les deux derniers chars... j'ai teste sur redirections_clean et il y a aussi ce bug

**Comment by Draeyo** [comment]
je pense savoir d'ou ca vient, je m'en occupe ce week end

**Comment by Freccia** [comment]
en fait le site enleve des slash, ce n'est pas la bonne commande!

**Comment by Freccia** [comment]
echo   \'  \"   ""  \"""  '\\' "\\''"   "   \\  \ \ \ \ \" \'"

**Comment by Freccia** [comment]
echo   \\'  \\"   ""  \\"""  '\\\\' "\\\\''"   "   \\\\  \\ \\ \\ \\ \\" \\'"

**Comment by Freccia** [comment]
sur ma branche (*apres le merge) d'ailleurs le Cmd-V ne marche pas du tout... Il met du trash au milieu de la ligne :(  Je vais voir ca demain, sinon la je vais exploser :O

**Comment by Freccia** [comment]
Bug found 

> while   (buf[++i]

became:

> while   (i < 3) ) 


 Closed.

**Comment by Freccia** [comment]
Bug found

> while (buf[++i]

became:

> while (i < 3)

Closed.

**Comment by dh4rm4** [comment]
Paste multi lines:
"""ls -l
ls
pwd"""
