### ISSUE TITLE
Substitution from history

### ISSUE THREAD

**Issue by dh4rm4** [segfault-team/42sh#86]
!420

**Comment by ayoubleg** [comment]
Le code que tu m'as laissé est pas bon sniff faut changer "l'offset" de pas mal de subtitution (le dernier argument) il "dit" le nombre de caractères à effacer, j'ai essayé de le faire sur mon pc mais j'ai trop de changements à faire pour que ça compile et ça ram lel
bref ... faut aussi virer le trim et pis c'est bon

**Comment by Draeyo** [comment]
chut ! t'es pas a jour

**Comment by Draeyo** [comment]
c'est ca de pas venir, apres ca suit plus rien

**Comment by ayoubleg** [comment]
:(

**Comment by ayoubleg** [comment]
Should be ok ?
